/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as taskRegistrySol from "./TaskRegistry.sol";
export type { taskRegistrySol };
export type { Counter } from "./Counter";
export type { MockUSDC } from "./MockUSDC";
export type { Treasury } from "./Treasury";
export * as factories from "./factories";
export { Counter__factory } from "./factories/Counter__factory";
export { MockUSDC__factory } from "./factories/MockUSDC__factory";
export type { IERC20 } from "./TaskRegistry.sol/IERC20";
export { IERC20__factory } from "./factories/TaskRegistry.sol/IERC20__factory";
export type { TaskRegistry } from "./TaskRegistry.sol/TaskRegistry";
export { TaskRegistry__factory } from "./factories/TaskRegistry.sol/TaskRegistry__factory";
export { Treasury__factory } from "./factories/Treasury__factory";
