/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Treasury {
  export type EscrowRecordStruct = {
    agentA: AddressLike;
    agentB: AddressLike;
    totalAmount: BigNumberish;
    levyAmount: BigNumberish;
    taskFee: BigNumberish;
    taskSpecHash: BytesLike;
    serviceId: string;
    status: BigNumberish;
    escrowedAt: BigNumberish;
    settledAt: BigNumberish;
    attestationHash: BytesLike;
  };

  export type EscrowRecordStructOutput = [
    agentA: string,
    agentB: string,
    totalAmount: bigint,
    levyAmount: bigint,
    taskFee: bigint,
    taskSpecHash: string,
    serviceId: string,
    status: bigint,
    escrowedAt: bigint,
    settledAt: bigint,
    attestationHash: string
  ] & {
    agentA: string;
    agentB: string;
    totalAmount: bigint;
    levyAmount: bigint;
    taskFee: bigint;
    taskSpecHash: string;
    serviceId: string;
    status: bigint;
    escrowedAt: bigint;
    settledAt: bigint;
    attestationHash: string;
  };

  export type LevyRecordStruct = {
    taskId: BytesLike;
    agentA: AddressLike;
    agentB: AddressLike;
    taskFee: BigNumberish;
    levyAmount: BigNumberish;
    timestamp: BigNumberish;
    attestationHash: BytesLike;
  };

  export type LevyRecordStructOutput = [
    taskId: string,
    agentA: string,
    agentB: string,
    taskFee: bigint,
    levyAmount: bigint,
    timestamp: bigint,
    attestationHash: string
  ] & {
    taskId: string;
    agentA: string;
    agentB: string;
    taskFee: bigint;
    levyAmount: bigint;
    timestamp: bigint;
    attestationHash: string;
  };
}

export interface TreasuryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISPUTE_WINDOW"
      | "MAX_LEVY_BPS"
      | "acceptOwnership"
      | "attestations"
      | "claimRefund"
      | "claimTimeoutRefund"
      | "disputeTask"
      | "escrowPayment"
      | "escrows"
      | "getEscrow"
      | "getLevyHistoryCount"
      | "getLevyRecord"
      | "getTreasuryBalance"
      | "levyBasisPoints"
      | "levyHistory"
      | "owner"
      | "pendingOwner"
      | "pendingWithdrawals"
      | "registerSpec"
      | "registerTEE"
      | "registeredSpecHashes"
      | "resolveDispute"
      | "revokeTEE"
      | "setLevyRate"
      | "specHashToServiceId"
      | "submitAttestation"
      | "totalLevyCollected"
      | "totalPendingWithdrawals"
      | "totalTaskVolume"
      | "totalTasksSettled"
      | "transferOwnership"
      | "verifiedTEEs"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttestationSubmitted"
      | "LevyRateUpdated"
      | "LevySettled"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "SpecRegistered"
      | "TEERegistered"
      | "TEERevoked"
      | "TaskDisputed"
      | "TaskEscrowed"
      | "TaskRefunded"
      | "WithdrawalClaimed"
      | "WithdrawalQueued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISPUTE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_LEVY_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attestations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTimeoutRefund",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowPayment",
    values: [BytesLike, AddressLike, BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "escrows", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLevyHistoryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLevyRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasuryBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "levyBasisPoints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "levyHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingWithdrawals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSpec",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerTEE",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredSpecHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTEE",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLevyRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "specHashToServiceId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitAttestation",
    values: [BytesLike, BytesLike, BytesLike, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalLevyCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPendingWithdrawals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTaskVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTasksSettled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedTEEs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DISPUTE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_LEVY_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTimeoutRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLevyHistoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLevyRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasuryBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "levyBasisPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "levyHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSpec",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerTEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredSpecHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeTEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setLevyRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "specHashToServiceId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLevyCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPendingWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTaskVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTasksSettled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedTEEs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AttestationSubmittedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    verifier: AddressLike,
    passed: boolean,
    score: string
  ];
  export type OutputTuple = [
    taskId: string,
    verifier: string,
    passed: boolean,
    score: string
  ];
  export interface OutputObject {
    taskId: string;
    verifier: string;
    passed: boolean;
    score: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LevyRateUpdatedEvent {
  export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish];
  export type OutputTuple = [oldRate: bigint, newRate: bigint];
  export interface OutputObject {
    oldRate: bigint;
    newRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LevySettledEvent {
  export type InputTuple = [
    taskId: BytesLike,
    agentA: AddressLike,
    agentB: AddressLike,
    taskFee: BigNumberish,
    levyAmount: BigNumberish,
    serviceId: string,
    attestationHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    agentA: string,
    agentB: string,
    taskFee: bigint,
    levyAmount: bigint,
    serviceId: string,
    attestationHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    taskId: string;
    agentA: string;
    agentB: string;
    taskFee: bigint;
    levyAmount: bigint;
    serviceId: string;
    attestationHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpecRegisteredEvent {
  export type InputTuple = [specHash: BytesLike, serviceId: string];
  export type OutputTuple = [specHash: string, serviceId: string];
  export interface OutputObject {
    specHash: string;
    serviceId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TEERegisteredEvent {
  export type InputTuple = [teeAddress: AddressLike];
  export type OutputTuple = [teeAddress: string];
  export interface OutputObject {
    teeAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TEERevokedEvent {
  export type InputTuple = [teeAddress: AddressLike];
  export type OutputTuple = [teeAddress: string];
  export interface OutputObject {
    teeAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskDisputedEvent {
  export type InputTuple = [taskId: BytesLike, disputedBy: AddressLike];
  export type OutputTuple = [taskId: string, disputedBy: string];
  export interface OutputObject {
    taskId: string;
    disputedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskEscrowedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    agentA: AddressLike,
    agentB: AddressLike,
    totalAmount: BigNumberish,
    levyAmount: BigNumberish,
    taskSpecHash: BytesLike,
    serviceId: string
  ];
  export type OutputTuple = [
    taskId: string,
    agentA: string,
    agentB: string,
    totalAmount: bigint,
    levyAmount: bigint,
    taskSpecHash: string,
    serviceId: string
  ];
  export interface OutputObject {
    taskId: string;
    agentA: string;
    agentB: string;
    totalAmount: bigint;
    levyAmount: bigint;
    taskSpecHash: string;
    serviceId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskRefundedEvent {
  export type InputTuple = [taskId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [taskId: string, amount: bigint];
  export interface OutputObject {
    taskId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalClaimedEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalQueuedEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Treasury extends BaseContract {
  connect(runner?: ContractRunner | null): Treasury;
  waitForDeployment(): Promise<this>;

  interface: TreasuryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISPUTE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  MAX_LEVY_BPS: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  attestations: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, boolean, string] & {
        taskId: string;
        specHash: string;
        outputHash: string;
        verifiedBy: string;
        timestamp: bigint;
        passed: boolean;
        score: string;
      }
    ],
    "view"
  >;

  claimRefund: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  claimTimeoutRefund: TypedContractMethod<
    [taskId: BytesLike],
    [void],
    "nonpayable"
  >;

  disputeTask: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  escrowPayment: TypedContractMethod<
    [
      taskId: BytesLike,
      agentB: AddressLike,
      taskSpecHash: BytesLike,
      serviceId: string
    ],
    [void],
    "payable"
  >;

  escrows: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        agentA: string;
        agentB: string;
        totalAmount: bigint;
        levyAmount: bigint;
        taskFee: bigint;
        taskSpecHash: string;
        serviceId: string;
        status: bigint;
        escrowedAt: bigint;
        settledAt: bigint;
        attestationHash: string;
      }
    ],
    "view"
  >;

  getEscrow: TypedContractMethod<
    [taskId: BytesLike],
    [Treasury.EscrowRecordStructOutput],
    "view"
  >;

  getLevyHistoryCount: TypedContractMethod<[], [bigint], "view">;

  getLevyRecord: TypedContractMethod<
    [index: BigNumberish],
    [Treasury.LevyRecordStructOutput],
    "view"
  >;

  getTreasuryBalance: TypedContractMethod<[], [bigint], "view">;

  levyBasisPoints: TypedContractMethod<[], [bigint], "view">;

  levyHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, string] & {
        taskId: string;
        agentA: string;
        agentB: string;
        taskFee: bigint;
        levyAmount: bigint;
        timestamp: bigint;
        attestationHash: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  pendingWithdrawals: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  registerSpec: TypedContractMethod<
    [specHash: BytesLike, serviceId: string],
    [void],
    "nonpayable"
  >;

  registerTEE: TypedContractMethod<
    [teeAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  registeredSpecHashes: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  resolveDispute: TypedContractMethod<
    [taskId: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeTEE: TypedContractMethod<
    [teeAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setLevyRate: TypedContractMethod<
    [newBasisPoints: BigNumberish],
    [void],
    "nonpayable"
  >;

  specHashToServiceId: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  submitAttestation: TypedContractMethod<
    [
      taskId: BytesLike,
      attestationHash: BytesLike,
      outputHash: BytesLike,
      passed: boolean,
      score: string
    ],
    [void],
    "nonpayable"
  >;

  totalLevyCollected: TypedContractMethod<[], [bigint], "view">;

  totalPendingWithdrawals: TypedContractMethod<[], [bigint], "view">;

  totalTaskVolume: TypedContractMethod<[], [bigint], "view">;

  totalTasksSettled: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifiedTEEs: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISPUTE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_LEVY_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "attestations"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, boolean, string] & {
        taskId: string;
        specHash: string;
        outputHash: string;
        verifiedBy: string;
        timestamp: bigint;
        passed: boolean;
        score: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTimeoutRefund"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disputeTask"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "escrowPayment"
  ): TypedContractMethod<
    [
      taskId: BytesLike,
      agentB: AddressLike,
      taskSpecHash: BytesLike,
      serviceId: string
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        agentA: string;
        agentB: string;
        totalAmount: bigint;
        levyAmount: bigint;
        taskFee: bigint;
        taskSpecHash: string;
        serviceId: string;
        status: bigint;
        escrowedAt: bigint;
        settledAt: bigint;
        attestationHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [Treasury.EscrowRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLevyHistoryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLevyRecord"
  ): TypedContractMethod<
    [index: BigNumberish],
    [Treasury.LevyRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTreasuryBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "levyBasisPoints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "levyHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, string] & {
        taskId: string;
        agentA: string;
        agentB: string;
        taskFee: bigint;
        levyAmount: bigint;
        timestamp: bigint;
        attestationHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingWithdrawals"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerSpec"
  ): TypedContractMethod<
    [specHash: BytesLike, serviceId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerTEE"
  ): TypedContractMethod<[teeAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registeredSpecHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeTEE"
  ): TypedContractMethod<[teeAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLevyRate"
  ): TypedContractMethod<[newBasisPoints: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "specHashToServiceId"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "submitAttestation"
  ): TypedContractMethod<
    [
      taskId: BytesLike,
      attestationHash: BytesLike,
      outputHash: BytesLike,
      passed: boolean,
      score: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalLevyCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPendingWithdrawals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalTaskVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalTasksSettled"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifiedTEEs"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AttestationSubmitted"
  ): TypedContractEvent<
    AttestationSubmittedEvent.InputTuple,
    AttestationSubmittedEvent.OutputTuple,
    AttestationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "LevyRateUpdated"
  ): TypedContractEvent<
    LevyRateUpdatedEvent.InputTuple,
    LevyRateUpdatedEvent.OutputTuple,
    LevyRateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LevySettled"
  ): TypedContractEvent<
    LevySettledEvent.InputTuple,
    LevySettledEvent.OutputTuple,
    LevySettledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SpecRegistered"
  ): TypedContractEvent<
    SpecRegisteredEvent.InputTuple,
    SpecRegisteredEvent.OutputTuple,
    SpecRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "TEERegistered"
  ): TypedContractEvent<
    TEERegisteredEvent.InputTuple,
    TEERegisteredEvent.OutputTuple,
    TEERegisteredEvent.OutputObject
  >;
  getEvent(
    key: "TEERevoked"
  ): TypedContractEvent<
    TEERevokedEvent.InputTuple,
    TEERevokedEvent.OutputTuple,
    TEERevokedEvent.OutputObject
  >;
  getEvent(
    key: "TaskDisputed"
  ): TypedContractEvent<
    TaskDisputedEvent.InputTuple,
    TaskDisputedEvent.OutputTuple,
    TaskDisputedEvent.OutputObject
  >;
  getEvent(
    key: "TaskEscrowed"
  ): TypedContractEvent<
    TaskEscrowedEvent.InputTuple,
    TaskEscrowedEvent.OutputTuple,
    TaskEscrowedEvent.OutputObject
  >;
  getEvent(
    key: "TaskRefunded"
  ): TypedContractEvent<
    TaskRefundedEvent.InputTuple,
    TaskRefundedEvent.OutputTuple,
    TaskRefundedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalClaimed"
  ): TypedContractEvent<
    WithdrawalClaimedEvent.InputTuple,
    WithdrawalClaimedEvent.OutputTuple,
    WithdrawalClaimedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalQueued"
  ): TypedContractEvent<
    WithdrawalQueuedEvent.InputTuple,
    WithdrawalQueuedEvent.OutputTuple,
    WithdrawalQueuedEvent.OutputObject
  >;

  filters: {
    "AttestationSubmitted(bytes32,address,bool,string)": TypedContractEvent<
      AttestationSubmittedEvent.InputTuple,
      AttestationSubmittedEvent.OutputTuple,
      AttestationSubmittedEvent.OutputObject
    >;
    AttestationSubmitted: TypedContractEvent<
      AttestationSubmittedEvent.InputTuple,
      AttestationSubmittedEvent.OutputTuple,
      AttestationSubmittedEvent.OutputObject
    >;

    "LevyRateUpdated(uint256,uint256)": TypedContractEvent<
      LevyRateUpdatedEvent.InputTuple,
      LevyRateUpdatedEvent.OutputTuple,
      LevyRateUpdatedEvent.OutputObject
    >;
    LevyRateUpdated: TypedContractEvent<
      LevyRateUpdatedEvent.InputTuple,
      LevyRateUpdatedEvent.OutputTuple,
      LevyRateUpdatedEvent.OutputObject
    >;

    "LevySettled(bytes32,address,address,uint256,uint256,string,bytes32,uint256)": TypedContractEvent<
      LevySettledEvent.InputTuple,
      LevySettledEvent.OutputTuple,
      LevySettledEvent.OutputObject
    >;
    LevySettled: TypedContractEvent<
      LevySettledEvent.InputTuple,
      LevySettledEvent.OutputTuple,
      LevySettledEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SpecRegistered(bytes32,string)": TypedContractEvent<
      SpecRegisteredEvent.InputTuple,
      SpecRegisteredEvent.OutputTuple,
      SpecRegisteredEvent.OutputObject
    >;
    SpecRegistered: TypedContractEvent<
      SpecRegisteredEvent.InputTuple,
      SpecRegisteredEvent.OutputTuple,
      SpecRegisteredEvent.OutputObject
    >;

    "TEERegistered(address)": TypedContractEvent<
      TEERegisteredEvent.InputTuple,
      TEERegisteredEvent.OutputTuple,
      TEERegisteredEvent.OutputObject
    >;
    TEERegistered: TypedContractEvent<
      TEERegisteredEvent.InputTuple,
      TEERegisteredEvent.OutputTuple,
      TEERegisteredEvent.OutputObject
    >;

    "TEERevoked(address)": TypedContractEvent<
      TEERevokedEvent.InputTuple,
      TEERevokedEvent.OutputTuple,
      TEERevokedEvent.OutputObject
    >;
    TEERevoked: TypedContractEvent<
      TEERevokedEvent.InputTuple,
      TEERevokedEvent.OutputTuple,
      TEERevokedEvent.OutputObject
    >;

    "TaskDisputed(bytes32,address)": TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;
    TaskDisputed: TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;

    "TaskEscrowed(bytes32,address,address,uint256,uint256,bytes32,string)": TypedContractEvent<
      TaskEscrowedEvent.InputTuple,
      TaskEscrowedEvent.OutputTuple,
      TaskEscrowedEvent.OutputObject
    >;
    TaskEscrowed: TypedContractEvent<
      TaskEscrowedEvent.InputTuple,
      TaskEscrowedEvent.OutputTuple,
      TaskEscrowedEvent.OutputObject
    >;

    "TaskRefunded(bytes32,uint256)": TypedContractEvent<
      TaskRefundedEvent.InputTuple,
      TaskRefundedEvent.OutputTuple,
      TaskRefundedEvent.OutputObject
    >;
    TaskRefunded: TypedContractEvent<
      TaskRefundedEvent.InputTuple,
      TaskRefundedEvent.OutputTuple,
      TaskRefundedEvent.OutputObject
    >;

    "WithdrawalClaimed(address,uint256)": TypedContractEvent<
      WithdrawalClaimedEvent.InputTuple,
      WithdrawalClaimedEvent.OutputTuple,
      WithdrawalClaimedEvent.OutputObject
    >;
    WithdrawalClaimed: TypedContractEvent<
      WithdrawalClaimedEvent.InputTuple,
      WithdrawalClaimedEvent.OutputTuple,
      WithdrawalClaimedEvent.OutputObject
    >;

    "WithdrawalQueued(address,uint256)": TypedContractEvent<
      WithdrawalQueuedEvent.InputTuple,
      WithdrawalQueuedEvent.OutputTuple,
      WithdrawalQueuedEvent.OutputObject
    >;
    WithdrawalQueued: TypedContractEvent<
      WithdrawalQueuedEvent.InputTuple,
      WithdrawalQueuedEvent.OutputTuple,
      WithdrawalQueuedEvent.OutputObject
    >;
  };
}
